name: Testing workflow for environment variables

on:
  schedule:
    # This now runs the moment after daily rewards reset, to run it before they reset run at "55 3 * * *"
    - cron: "5 4 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.7"
          cache: "npm"
      - run: npm install
      - run: npm start
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          WEBHOOK_URL: ${{ secrets.TEST }}
