name: Testing workflow for environment variables

on: push

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.7"
          cache: "npm"
      - run: npm install
      - run: npm start
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      - uses: actions/upload-artifact@v3
        with:
          name: log
          path: log1.png
